version: '3'

services:
  # gulp用コンテナの設定
  gulp:
    # dockerfileのパス
    build: ./gulp
    # マウントするフォルダ
    volumes:
      - ./css:/my_gulp/css
      - ./scss:/my_gulp/scss
      - ./swagger-components:/my_gulp/swagger-components
      - ./swagger-edited:/my_gulp/swagger-edited
      - ./swagger-merged:/my_gulp/swagger-merged
      - ./gulp/package.json:/my_gulp/package.json
      - ./gulp/package-lock.json:/my_gulp/package-lock.json
      - ./gulp/gulpfile.js:/my_gulp/gulpfile.js
